# Generated by Django 3.1.7 on 2021-03-01 02:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='dt_cadastro')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='dt_atualizacao', null=True)),
                ('id_author', models.BigAutoField(db_column='id_autor', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='nome_autor', max_length=255)),
            ],
            options={
                'verbose_name': 'Autor',
                'verbose_name_plural': 'Autores',
                'db_table': 'autor',
                'ordering': ['id_author'],
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='dt_cadastro')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='dt_atualizacao', null=True)),
                ('id_book', models.BigAutoField(db_column='id_livro', primary_key=True, serialize=False)),
                ('book_title', models.CharField(db_column='titulo_livro', max_length=255)),
                ('date_booking', models.DateTimeField(blank=True, db_column='dt_reserva', null=True)),
                ('author', models.ForeignKey(db_column='id_autor', on_delete=django.db.models.deletion.CASCADE, related_name='book_set', to='books.author')),
            ],
            options={
                'verbose_name': 'Livro',
                'verbose_name_plural': 'Livros',
                'db_table': 'livro',
                'ordering': ['id_book'],
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='dt_cadastro')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='dt_atualizacao', null=True)),
                ('id_client', models.BigAutoField(db_column='id_cliente', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='nome_cliente', max_length=255)),
                ('active', models.BooleanField(db_column='ativo', default=True)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'db_table': 'cliente',
                'ordering': ['id_client'],
            },
        ),
        migrations.CreateModel(
            name='Borrow',
            fields=[
                ('id_borrow', models.BigAutoField(db_column='id_emprestimo', primary_key=True, serialize=False)),
                ('date_borrow', models.DateTimeField(auto_now_add=True, db_column='dt_emprestimo', null=True)),
                ('date_devolution', models.DateTimeField(blank=True, db_column='dt_devolucao', null=True)),
                ('book', models.ForeignKey(db_column='id_livro', on_delete=django.db.models.deletion.CASCADE, related_name='borrow_set', to='books.book')),
                ('client', models.ForeignKey(db_column='id_cliente', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='borrow_set', to='books.client')),
            ],
            options={
                'verbose_name': 'Emprestimo',
                'verbose_name_plural': 'Emprestimos',
                'db_table': 'emprestimo',
                'ordering': ['id_borrow'],
            },
        ),
    ]
